version: "3.9"
services:
  frontend:
    build: ./frontend
    depends_on:
      - api
    ports:
      - 5173:5173
    networks:
      - network-backend
  postgres:
    container_name: courier_database
    image: postgres:latest
    hostname: postgres
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=courier
    networks:
      - network-backend
    volumes:
      - ./pgData:/var/lib/psotgresql/data

  api:
    build: ./backend
    depends_on:
      - postgres
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - SECRET_KEY=SECRETHEHEHE
    networks:
      - network-backend
    restart: always

networks:
  network-backend:

volumes:
  postgres_data:
